/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformOnboardingRouteImport } from './routes/_platform.onboarding'
import { Route as PlatformLoginRouteImport } from './routes/_platform.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOrgChartRouteImport } from './routes/_app.org-chart'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal.portal.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppPerformanceIndexRouteImport } from './routes/_app.performance.index'
import { Route as AppPayrollIndexRouteImport } from './routes/_app.payroll.index'
import { Route as AppLeaveIndexRouteImport } from './routes/_app.leave.index'
import { Route as AppHelpdeskIndexRouteImport } from './routes/_app.helpdesk.index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app.expenses.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app.employees.index'
import { Route as AppCandidatesIndexRouteImport } from './routes/_app.candidates.index'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app.attendance.index'
import { Route as PlatformOnboardingReviewRouteImport } from './routes/_platform.onboarding.review'
import { Route as PlatformOnboardingBrandRouteImport } from './routes/_platform.onboarding.brand'
import { Route as PlatformOnboardingAdminRouteImport } from './routes/_platform.onboarding.admin'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppSettingsAttendanceRouteImport } from './routes/_app.settings.attendance'
import { Route as AppReportsReportSlugRouteImport } from './routes/_app.reports.$reportSlug'
import { Route as AppPerformanceTeamRouteImport } from './routes/_app.performance.team'
import { Route as AppPerformanceReviewsRouteImport } from './routes/_app.performance.reviews'
import { Route as AppPerformanceGoalsRouteImport } from './routes/_app.performance.goals'
import { Route as AppPerformanceCalibrationRouteImport } from './routes/_app.performance.calibration'
import { Route as AppPerformanceAdminRouteImport } from './routes/_app.performance.admin'
import { Route as AppPayrollPayslipsRouteImport } from './routes/_app.payroll.payslips'
import { Route as AppPayrollDeclarationsRouteImport } from './routes/_app.payroll.declarations'
import { Route as AppLeaveRequestsRouteImport } from './routes/_app.leave.requests'
import { Route as AppLeaveCalendarRouteImport } from './routes/_app.leave.calendar'
import { Route as AppLeaveBalancesRouteImport } from './routes/_app.leave.balances'
import { Route as AppLeaveApprovalsRouteImport } from './routes/_app.leave.approvals'
import { Route as AppLeaveApplyRouteImport } from './routes/_app.leave.apply'
import { Route as AppHelpdeskNewRouteImport } from './routes/_app.helpdesk.new'
import { Route as AppExpensesNewRouteImport } from './routes/_app.expenses.new'
import { Route as AppEmployeesNewRouteImport } from './routes/_app.employees.new'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app.employees.$employeeId'
import { Route as AppCandidatesInviteRouteImport } from './routes/_app.candidates.invite'
import { Route as AppCandidatesCandidateIdRouteImport } from './routes/_app.candidates.$candidateId'
import { Route as AppAttendanceTeamRouteImport } from './routes/_app.attendance.team'
import { Route as AppAttendanceRegularizationRouteImport } from './routes/_app.attendance.regularization'
import { Route as AppAttendanceRecordsRouteImport } from './routes/_app.attendance.records'
import { Route as AdminAdminTenantsRouteImport } from './routes/_admin.admin.tenants'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin.admin.login'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as PortalPortalPipelineIdIndexRouteImport } from './routes/_portal.portal.$pipelineId.index'
import { Route as AppSettingsRolesIndexRouteImport } from './routes/_app.settings.roles.index'
import { Route as AppSettingsPayrollIndexRouteImport } from './routes/_app.settings.payroll.index'
import { Route as AppSettingsLeaveIndexRouteImport } from './routes/_app.settings.leave.index'
import { Route as AppSettingsFormsIndexRouteImport } from './routes/_app.settings.forms.index'
import { Route as AppReportsBuilderIndexRouteImport } from './routes/_app.reports.builder.index'
import { Route as AppPayrollRunsIndexRouteImport } from './routes/_app.payroll.runs.index'
import { Route as AppAttendanceRegularizationIndexRouteImport } from './routes/_app.attendance.regularization.index'
import { Route as PortalPortalPipelineIdOfferRouteImport } from './routes/_portal.portal.$pipelineId.offer'
import { Route as PortalPortalPipelineIdFormRouteImport } from './routes/_portal.portal.$pipelineId.form'
import { Route as AppSettingsRolesNewRouteImport } from './routes/_app.settings.roles.new'
import { Route as AppSettingsRolesDelegationRouteImport } from './routes/_app.settings.roles.delegation'
import { Route as AppSettingsRolesAuditRouteImport } from './routes/_app.settings.roles.audit'
import { Route as AppSettingsRolesAssignmentsRouteImport } from './routes/_app.settings.roles.assignments'
import { Route as AppSettingsPayrollStructuresRouteImport } from './routes/_app.settings.payroll.structures'
import { Route as AppSettingsLeavePoliciesRouteImport } from './routes/_app.settings.leave.policies'
import { Route as AppSettingsHiringRejectionReasonsRouteImport } from './routes/_app.settings.hiring.rejection-reasons'
import { Route as AppSettingsFormsNewRouteImport } from './routes/_app.settings.forms.new'
import { Route as AppSettingsCompanyWorkCalendarRouteImport } from './routes/_app.settings.company.work-calendar'
import { Route as AppSettingsCompanyHolidaysRouteImport } from './routes/_app.settings.company.holidays'
import { Route as AppSettingsCompanyDesignationsRouteImport } from './routes/_app.settings.company.designations'
import { Route as AppSettingsCompanyDepartmentsRouteImport } from './routes/_app.settings.company.departments'
import { Route as AppReportsBuilderReportIdRouteImport } from './routes/_app.reports.builder.$reportId'
import { Route as AppPerformanceTeamEmployeeIdRouteImport } from './routes/_app.performance.team.$employeeId'
import { Route as AppPerformanceReviewsReviewIdRouteImport } from './routes/_app.performance.reviews.$reviewId'
import { Route as AppPayrollRunsRunIdRouteImport } from './routes/_app.payroll.runs.$runId'
import { Route as AppEmployeesEmployeeIdEditRouteImport } from './routes/_app.employees.$employeeId.edit'
import { Route as AppAttendanceRegularizationApprovalsRouteImport } from './routes/_app.attendance.regularization.approvals'
import { Route as AdminAdminTenantsNewRouteImport } from './routes/_admin.admin.tenants.new'
import { Route as AdminAdminTenantsTenantIdRouteImport } from './routes/_admin.admin.tenants.$tenantId'
import { Route as AppSettingsRolesRoleIdIndexRouteImport } from './routes/_app.settings.roles.$roleId.index'
import { Route as AppSettingsFormsFormIdIndexRouteImport } from './routes/_app.settings.forms.$formId.index'
import { Route as AppSettingsRolesRoleIdEditRouteImport } from './routes/_app.settings.roles.$roleId.edit'
import { Route as AppSettingsFormsFormIdSubmissionsRouteImport } from './routes/_app.settings.forms.$formId.submissions'
import { Route as AppSettingsFormsFormIdPreviewRouteImport } from './routes/_app.settings.forms.$formId.preview'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOnboardingRoute = PlatformOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PlatformRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgChartRoute = AppOrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceIndexRoute = AppPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveIndexRoute = AppLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskIndexRoute = AppHelpdeskIndexRouteImport.update({
  id: '/helpdesk/',
  path: '/helpdesk/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AppRoute,
} as any)
const PlatformOnboardingReviewRoute =
  PlatformOnboardingReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => PlatformOnboardingRoute,
  } as any)
const PlatformOnboardingBrandRoute = PlatformOnboardingBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => PlatformOnboardingRoute,
} as any)
const PlatformOnboardingAdminRoute = PlatformOnboardingAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PlatformOnboardingRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAttendanceRoute = AppSettingsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsReportSlugRoute = AppReportsReportSlugRouteImport.update({
  id: '/reports/$reportSlug',
  path: '/reports/$reportSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceTeamRoute = AppPerformanceTeamRouteImport.update({
  id: '/performance/team',
  path: '/performance/team',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceReviewsRoute = AppPerformanceReviewsRouteImport.update({
  id: '/performance/reviews',
  path: '/performance/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceGoalsRoute = AppPerformanceGoalsRouteImport.update({
  id: '/performance/goals',
  path: '/performance/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceCalibrationRoute =
  AppPerformanceCalibrationRouteImport.update({
    id: '/performance/calibration',
    path: '/performance/calibration',
    getParentRoute: () => AppRoute,
  } as any)
const AppPerformanceAdminRoute = AppPerformanceAdminRouteImport.update({
  id: '/performance/admin',
  path: '/performance/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollPayslipsRoute = AppPayrollPayslipsRouteImport.update({
  id: '/payroll/payslips',
  path: '/payroll/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollDeclarationsRoute = AppPayrollDeclarationsRouteImport.update({
  id: '/payroll/declarations',
  path: '/payroll/declarations',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsRoute = AppLeaveRequestsRouteImport.update({
  id: '/leave/requests',
  path: '/leave/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveCalendarRoute = AppLeaveCalendarRouteImport.update({
  id: '/leave/calendar',
  path: '/leave/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveBalancesRoute = AppLeaveBalancesRouteImport.update({
  id: '/leave/balances',
  path: '/leave/balances',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApprovalsRoute = AppLeaveApprovalsRouteImport.update({
  id: '/leave/approvals',
  path: '/leave/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApplyRoute = AppLeaveApplyRouteImport.update({
  id: '/leave/apply',
  path: '/leave/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskNewRoute = AppHelpdeskNewRouteImport.update({
  id: '/helpdesk/new',
  path: '/helpdesk/new',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesNewRoute = AppEmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppCandidatesInviteRoute = AppCandidatesInviteRouteImport.update({
  id: '/candidates/invite',
  path: '/candidates/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesCandidateIdRoute =
  AppCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceTeamRoute = AppAttendanceTeamRouteImport.update({
  id: '/attendance/team',
  path: '/attendance/team',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRegularizationRoute =
  AppAttendanceRegularizationRouteImport.update({
    id: '/attendance/regularization',
    path: '/attendance/regularization',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceRecordsRoute = AppAttendanceRecordsRouteImport.update({
  id: '/attendance/records',
  path: '/attendance/records',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminTenantsRoute = AdminAdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const PortalPortalPipelineIdIndexRoute =
  PortalPortalPipelineIdIndexRouteImport.update({
    id: '/portal/$pipelineId/',
    path: '/portal/$pipelineId/',
    getParentRoute: () => PortalRoute,
  } as any)
const AppSettingsRolesIndexRoute = AppSettingsRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRolesRoute,
} as any)
const AppSettingsPayrollIndexRoute = AppSettingsPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLeaveIndexRoute = AppSettingsLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFormsIndexRoute = AppSettingsFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsBuilderIndexRoute = AppReportsBuilderIndexRouteImport.update({
  id: '/reports/builder/',
  path: '/reports/builder/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRunsIndexRoute = AppPayrollRunsIndexRouteImport.update({
  id: '/payroll/runs/',
  path: '/payroll/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRegularizationIndexRoute =
  AppAttendanceRegularizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAttendanceRegularizationRoute,
  } as any)
const PortalPortalPipelineIdOfferRoute =
  PortalPortalPipelineIdOfferRouteImport.update({
    id: '/portal/$pipelineId/offer',
    path: '/portal/$pipelineId/offer',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalPipelineIdFormRoute =
  PortalPortalPipelineIdFormRouteImport.update({
    id: '/portal/$pipelineId/form',
    path: '/portal/$pipelineId/form',
    getParentRoute: () => PortalRoute,
  } as any)
const AppSettingsRolesNewRoute = AppSettingsRolesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSettingsRolesRoute,
} as any)
const AppSettingsRolesDelegationRoute =
  AppSettingsRolesDelegationRouteImport.update({
    id: '/delegation',
    path: '/delegation',
    getParentRoute: () => AppSettingsRolesRoute,
  } as any)
const AppSettingsRolesAuditRoute = AppSettingsRolesAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRolesRoute,
} as any)
const AppSettingsRolesAssignmentsRoute =
  AppSettingsRolesAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AppSettingsRolesRoute,
  } as any)
const AppSettingsPayrollStructuresRoute =
  AppSettingsPayrollStructuresRouteImport.update({
    id: '/payroll/structures',
    path: '/payroll/structures',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsLeavePoliciesRoute =
  AppSettingsLeavePoliciesRouteImport.update({
    id: '/leave/policies',
    path: '/leave/policies',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsHiringRejectionReasonsRoute =
  AppSettingsHiringRejectionReasonsRouteImport.update({
    id: '/hiring/rejection-reasons',
    path: '/hiring/rejection-reasons',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsFormsNewRoute = AppSettingsFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCompanyWorkCalendarRoute =
  AppSettingsCompanyWorkCalendarRouteImport.update({
    id: '/work-calendar',
    path: '/work-calendar',
    getParentRoute: () => AppSettingsCompanyRoute,
  } as any)
const AppSettingsCompanyHolidaysRoute =
  AppSettingsCompanyHolidaysRouteImport.update({
    id: '/holidays',
    path: '/holidays',
    getParentRoute: () => AppSettingsCompanyRoute,
  } as any)
const AppSettingsCompanyDesignationsRoute =
  AppSettingsCompanyDesignationsRouteImport.update({
    id: '/designations',
    path: '/designations',
    getParentRoute: () => AppSettingsCompanyRoute,
  } as any)
const AppSettingsCompanyDepartmentsRoute =
  AppSettingsCompanyDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AppSettingsCompanyRoute,
  } as any)
const AppReportsBuilderReportIdRoute =
  AppReportsBuilderReportIdRouteImport.update({
    id: '/reports/builder/$reportId',
    path: '/reports/builder/$reportId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPerformanceTeamEmployeeIdRoute =
  AppPerformanceTeamEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AppPerformanceTeamRoute,
  } as any)
const AppPerformanceReviewsReviewIdRoute =
  AppPerformanceReviewsReviewIdRouteImport.update({
    id: '/$reviewId',
    path: '/$reviewId',
    getParentRoute: () => AppPerformanceReviewsRoute,
  } as any)
const AppPayrollRunsRunIdRoute = AppPayrollRunsRunIdRouteImport.update({
  id: '/payroll/runs/$runId',
  path: '/payroll/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesEmployeeIdEditRoute =
  AppEmployeesEmployeeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppEmployeesEmployeeIdRoute,
  } as any)
const AppAttendanceRegularizationApprovalsRoute =
  AppAttendanceRegularizationApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AppAttendanceRegularizationRoute,
  } as any)
const AdminAdminTenantsNewRoute = AdminAdminTenantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminTenantsRoute,
} as any)
const AdminAdminTenantsTenantIdRoute =
  AdminAdminTenantsTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => AdminAdminTenantsRoute,
  } as any)
const AppSettingsRolesRoleIdIndexRoute =
  AppSettingsRolesRoleIdIndexRouteImport.update({
    id: '/$roleId/',
    path: '/$roleId/',
    getParentRoute: () => AppSettingsRolesRoute,
  } as any)
const AppSettingsFormsFormIdIndexRoute =
  AppSettingsFormsFormIdIndexRouteImport.update({
    id: '/forms/$formId/',
    path: '/forms/$formId/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsRolesRoleIdEditRoute =
  AppSettingsRolesRoleIdEditRouteImport.update({
    id: '/$roleId/edit',
    path: '/$roleId/edit',
    getParentRoute: () => AppSettingsRolesRoute,
  } as any)
const AppSettingsFormsFormIdSubmissionsRoute =
  AppSettingsFormsFormIdSubmissionsRouteImport.update({
    id: '/forms/$formId/submissions',
    path: '/forms/$formId/submissions',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsFormsFormIdPreviewRoute =
  AppSettingsFormsFormIdPreviewRouteImport.update({
    id: '/forms/$formId/preview',
    path: '/forms/$formId/preview',
    getParentRoute: () => AppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/me': typeof AppMeRoute
  '/notifications': typeof AppNotificationsRoute
  '/org-chart': typeof AppOrgChartRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof PlatformLoginRoute
  '/onboarding': typeof PlatformOnboardingRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/tenants': typeof AdminAdminTenantsRouteWithChildren
  '/attendance/records': typeof AppAttendanceRecordsRoute
  '/attendance/regularization': typeof AppAttendanceRegularizationRouteWithChildren
  '/attendance/team': typeof AppAttendanceTeamRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/candidates/invite': typeof AppCandidatesInviteRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRouteWithChildren
  '/employees/new': typeof AppEmployeesNewRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/helpdesk/new': typeof AppHelpdeskNewRoute
  '/leave/apply': typeof AppLeaveApplyRoute
  '/leave/approvals': typeof AppLeaveApprovalsRoute
  '/leave/balances': typeof AppLeaveBalancesRoute
  '/leave/calendar': typeof AppLeaveCalendarRoute
  '/leave/requests': typeof AppLeaveRequestsRoute
  '/payroll/declarations': typeof AppPayrollDeclarationsRoute
  '/payroll/payslips': typeof AppPayrollPayslipsRoute
  '/performance/admin': typeof AppPerformanceAdminRoute
  '/performance/calibration': typeof AppPerformanceCalibrationRoute
  '/performance/goals': typeof AppPerformanceGoalsRoute
  '/performance/reviews': typeof AppPerformanceReviewsRouteWithChildren
  '/performance/team': typeof AppPerformanceTeamRouteWithChildren
  '/reports/$reportSlug': typeof AppReportsReportSlugRoute
  '/settings/attendance': typeof AppSettingsAttendanceRoute
  '/settings/company': typeof AppSettingsCompanyRouteWithChildren
  '/settings/roles': typeof AppSettingsRolesRouteWithChildren
  '/onboarding/admin': typeof PlatformOnboardingAdminRoute
  '/onboarding/brand': typeof PlatformOnboardingBrandRoute
  '/onboarding/review': typeof PlatformOnboardingReviewRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/candidates/': typeof AppCandidatesIndexRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/helpdesk/': typeof AppHelpdeskIndexRoute
  '/leave/': typeof AppLeaveIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/performance/': typeof AppPerformanceIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/admin/tenants/$tenantId': typeof AdminAdminTenantsTenantIdRoute
  '/admin/tenants/new': typeof AdminAdminTenantsNewRoute
  '/attendance/regularization/approvals': typeof AppAttendanceRegularizationApprovalsRoute
  '/employees/$employeeId/edit': typeof AppEmployeesEmployeeIdEditRoute
  '/payroll/runs/$runId': typeof AppPayrollRunsRunIdRoute
  '/performance/reviews/$reviewId': typeof AppPerformanceReviewsReviewIdRoute
  '/performance/team/$employeeId': typeof AppPerformanceTeamEmployeeIdRoute
  '/reports/builder/$reportId': typeof AppReportsBuilderReportIdRoute
  '/settings/company/departments': typeof AppSettingsCompanyDepartmentsRoute
  '/settings/company/designations': typeof AppSettingsCompanyDesignationsRoute
  '/settings/company/holidays': typeof AppSettingsCompanyHolidaysRoute
  '/settings/company/work-calendar': typeof AppSettingsCompanyWorkCalendarRoute
  '/settings/forms/new': typeof AppSettingsFormsNewRoute
  '/settings/hiring/rejection-reasons': typeof AppSettingsHiringRejectionReasonsRoute
  '/settings/leave/policies': typeof AppSettingsLeavePoliciesRoute
  '/settings/payroll/structures': typeof AppSettingsPayrollStructuresRoute
  '/settings/roles/assignments': typeof AppSettingsRolesAssignmentsRoute
  '/settings/roles/audit': typeof AppSettingsRolesAuditRoute
  '/settings/roles/delegation': typeof AppSettingsRolesDelegationRoute
  '/settings/roles/new': typeof AppSettingsRolesNewRoute
  '/portal/$pipelineId/form': typeof PortalPortalPipelineIdFormRoute
  '/portal/$pipelineId/offer': typeof PortalPortalPipelineIdOfferRoute
  '/attendance/regularization/': typeof AppAttendanceRegularizationIndexRoute
  '/payroll/runs/': typeof AppPayrollRunsIndexRoute
  '/reports/builder/': typeof AppReportsBuilderIndexRoute
  '/settings/forms/': typeof AppSettingsFormsIndexRoute
  '/settings/leave/': typeof AppSettingsLeaveIndexRoute
  '/settings/payroll/': typeof AppSettingsPayrollIndexRoute
  '/settings/roles/': typeof AppSettingsRolesIndexRoute
  '/portal/$pipelineId/': typeof PortalPortalPipelineIdIndexRoute
  '/settings/forms/$formId/preview': typeof AppSettingsFormsFormIdPreviewRoute
  '/settings/forms/$formId/submissions': typeof AppSettingsFormsFormIdSubmissionsRoute
  '/settings/roles/$roleId/edit': typeof AppSettingsRolesRoleIdEditRoute
  '/settings/forms/$formId/': typeof AppSettingsFormsFormIdIndexRoute
  '/settings/roles/$roleId/': typeof AppSettingsRolesRoleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/dashboard': typeof AppDashboardRoute
  '/me': typeof AppMeRoute
  '/notifications': typeof AppNotificationsRoute
  '/org-chart': typeof AppOrgChartRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof PlatformLoginRoute
  '/onboarding': typeof PlatformOnboardingRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/tenants': typeof AdminAdminTenantsRouteWithChildren
  '/attendance/records': typeof AppAttendanceRecordsRoute
  '/attendance/team': typeof AppAttendanceTeamRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/candidates/invite': typeof AppCandidatesInviteRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRouteWithChildren
  '/employees/new': typeof AppEmployeesNewRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/helpdesk/new': typeof AppHelpdeskNewRoute
  '/leave/apply': typeof AppLeaveApplyRoute
  '/leave/approvals': typeof AppLeaveApprovalsRoute
  '/leave/balances': typeof AppLeaveBalancesRoute
  '/leave/calendar': typeof AppLeaveCalendarRoute
  '/leave/requests': typeof AppLeaveRequestsRoute
  '/payroll/declarations': typeof AppPayrollDeclarationsRoute
  '/payroll/payslips': typeof AppPayrollPayslipsRoute
  '/performance/admin': typeof AppPerformanceAdminRoute
  '/performance/calibration': typeof AppPerformanceCalibrationRoute
  '/performance/goals': typeof AppPerformanceGoalsRoute
  '/performance/reviews': typeof AppPerformanceReviewsRouteWithChildren
  '/performance/team': typeof AppPerformanceTeamRouteWithChildren
  '/reports/$reportSlug': typeof AppReportsReportSlugRoute
  '/settings/attendance': typeof AppSettingsAttendanceRoute
  '/settings/company': typeof AppSettingsCompanyRouteWithChildren
  '/onboarding/admin': typeof PlatformOnboardingAdminRoute
  '/onboarding/brand': typeof PlatformOnboardingBrandRoute
  '/onboarding/review': typeof PlatformOnboardingReviewRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/candidates': typeof AppCandidatesIndexRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/helpdesk': typeof AppHelpdeskIndexRoute
  '/leave': typeof AppLeaveIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/performance': typeof AppPerformanceIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/portal': typeof PortalPortalIndexRoute
  '/admin/tenants/$tenantId': typeof AdminAdminTenantsTenantIdRoute
  '/admin/tenants/new': typeof AdminAdminTenantsNewRoute
  '/attendance/regularization/approvals': typeof AppAttendanceRegularizationApprovalsRoute
  '/employees/$employeeId/edit': typeof AppEmployeesEmployeeIdEditRoute
  '/payroll/runs/$runId': typeof AppPayrollRunsRunIdRoute
  '/performance/reviews/$reviewId': typeof AppPerformanceReviewsReviewIdRoute
  '/performance/team/$employeeId': typeof AppPerformanceTeamEmployeeIdRoute
  '/reports/builder/$reportId': typeof AppReportsBuilderReportIdRoute
  '/settings/company/departments': typeof AppSettingsCompanyDepartmentsRoute
  '/settings/company/designations': typeof AppSettingsCompanyDesignationsRoute
  '/settings/company/holidays': typeof AppSettingsCompanyHolidaysRoute
  '/settings/company/work-calendar': typeof AppSettingsCompanyWorkCalendarRoute
  '/settings/forms/new': typeof AppSettingsFormsNewRoute
  '/settings/hiring/rejection-reasons': typeof AppSettingsHiringRejectionReasonsRoute
  '/settings/leave/policies': typeof AppSettingsLeavePoliciesRoute
  '/settings/payroll/structures': typeof AppSettingsPayrollStructuresRoute
  '/settings/roles/assignments': typeof AppSettingsRolesAssignmentsRoute
  '/settings/roles/audit': typeof AppSettingsRolesAuditRoute
  '/settings/roles/delegation': typeof AppSettingsRolesDelegationRoute
  '/settings/roles/new': typeof AppSettingsRolesNewRoute
  '/portal/$pipelineId/form': typeof PortalPortalPipelineIdFormRoute
  '/portal/$pipelineId/offer': typeof PortalPortalPipelineIdOfferRoute
  '/attendance/regularization': typeof AppAttendanceRegularizationIndexRoute
  '/payroll/runs': typeof AppPayrollRunsIndexRoute
  '/reports/builder': typeof AppReportsBuilderIndexRoute
  '/settings/forms': typeof AppSettingsFormsIndexRoute
  '/settings/leave': typeof AppSettingsLeaveIndexRoute
  '/settings/payroll': typeof AppSettingsPayrollIndexRoute
  '/settings/roles': typeof AppSettingsRolesIndexRoute
  '/portal/$pipelineId': typeof PortalPortalPipelineIdIndexRoute
  '/settings/forms/$formId/preview': typeof AppSettingsFormsFormIdPreviewRoute
  '/settings/forms/$formId/submissions': typeof AppSettingsFormsFormIdSubmissionsRoute
  '/settings/roles/$roleId/edit': typeof AppSettingsRolesRoleIdEditRoute
  '/settings/forms/$formId': typeof AppSettingsFormsFormIdIndexRoute
  '/settings/roles/$roleId': typeof AppSettingsRolesRoleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/me': typeof AppMeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/org-chart': typeof AppOrgChartRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_platform/login': typeof PlatformLoginRoute
  '/_platform/onboarding': typeof PlatformOnboardingRouteWithChildren
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/tenants': typeof AdminAdminTenantsRouteWithChildren
  '/_app/attendance/records': typeof AppAttendanceRecordsRoute
  '/_app/attendance/regularization': typeof AppAttendanceRegularizationRouteWithChildren
  '/_app/attendance/team': typeof AppAttendanceTeamRoute
  '/_app/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/_app/candidates/invite': typeof AppCandidatesInviteRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRouteWithChildren
  '/_app/employees/new': typeof AppEmployeesNewRoute
  '/_app/expenses/new': typeof AppExpensesNewRoute
  '/_app/helpdesk/new': typeof AppHelpdeskNewRoute
  '/_app/leave/apply': typeof AppLeaveApplyRoute
  '/_app/leave/approvals': typeof AppLeaveApprovalsRoute
  '/_app/leave/balances': typeof AppLeaveBalancesRoute
  '/_app/leave/calendar': typeof AppLeaveCalendarRoute
  '/_app/leave/requests': typeof AppLeaveRequestsRoute
  '/_app/payroll/declarations': typeof AppPayrollDeclarationsRoute
  '/_app/payroll/payslips': typeof AppPayrollPayslipsRoute
  '/_app/performance/admin': typeof AppPerformanceAdminRoute
  '/_app/performance/calibration': typeof AppPerformanceCalibrationRoute
  '/_app/performance/goals': typeof AppPerformanceGoalsRoute
  '/_app/performance/reviews': typeof AppPerformanceReviewsRouteWithChildren
  '/_app/performance/team': typeof AppPerformanceTeamRouteWithChildren
  '/_app/reports/$reportSlug': typeof AppReportsReportSlugRoute
  '/_app/settings/attendance': typeof AppSettingsAttendanceRoute
  '/_app/settings/company': typeof AppSettingsCompanyRouteWithChildren
  '/_app/settings/roles': typeof AppSettingsRolesRouteWithChildren
  '/_platform/onboarding/admin': typeof PlatformOnboardingAdminRoute
  '/_platform/onboarding/brand': typeof PlatformOnboardingBrandRoute
  '/_platform/onboarding/review': typeof PlatformOnboardingReviewRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/candidates/': typeof AppCandidatesIndexRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/helpdesk/': typeof AppHelpdeskIndexRoute
  '/_app/leave/': typeof AppLeaveIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/performance/': typeof AppPerformanceIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_admin/admin/tenants/$tenantId': typeof AdminAdminTenantsTenantIdRoute
  '/_admin/admin/tenants/new': typeof AdminAdminTenantsNewRoute
  '/_app/attendance/regularization/approvals': typeof AppAttendanceRegularizationApprovalsRoute
  '/_app/employees/$employeeId/edit': typeof AppEmployeesEmployeeIdEditRoute
  '/_app/payroll/runs/$runId': typeof AppPayrollRunsRunIdRoute
  '/_app/performance/reviews/$reviewId': typeof AppPerformanceReviewsReviewIdRoute
  '/_app/performance/team/$employeeId': typeof AppPerformanceTeamEmployeeIdRoute
  '/_app/reports/builder/$reportId': typeof AppReportsBuilderReportIdRoute
  '/_app/settings/company/departments': typeof AppSettingsCompanyDepartmentsRoute
  '/_app/settings/company/designations': typeof AppSettingsCompanyDesignationsRoute
  '/_app/settings/company/holidays': typeof AppSettingsCompanyHolidaysRoute
  '/_app/settings/company/work-calendar': typeof AppSettingsCompanyWorkCalendarRoute
  '/_app/settings/forms/new': typeof AppSettingsFormsNewRoute
  '/_app/settings/hiring/rejection-reasons': typeof AppSettingsHiringRejectionReasonsRoute
  '/_app/settings/leave/policies': typeof AppSettingsLeavePoliciesRoute
  '/_app/settings/payroll/structures': typeof AppSettingsPayrollStructuresRoute
  '/_app/settings/roles/assignments': typeof AppSettingsRolesAssignmentsRoute
  '/_app/settings/roles/audit': typeof AppSettingsRolesAuditRoute
  '/_app/settings/roles/delegation': typeof AppSettingsRolesDelegationRoute
  '/_app/settings/roles/new': typeof AppSettingsRolesNewRoute
  '/_portal/portal/$pipelineId/form': typeof PortalPortalPipelineIdFormRoute
  '/_portal/portal/$pipelineId/offer': typeof PortalPortalPipelineIdOfferRoute
  '/_app/attendance/regularization/': typeof AppAttendanceRegularizationIndexRoute
  '/_app/payroll/runs/': typeof AppPayrollRunsIndexRoute
  '/_app/reports/builder/': typeof AppReportsBuilderIndexRoute
  '/_app/settings/forms/': typeof AppSettingsFormsIndexRoute
  '/_app/settings/leave/': typeof AppSettingsLeaveIndexRoute
  '/_app/settings/payroll/': typeof AppSettingsPayrollIndexRoute
  '/_app/settings/roles/': typeof AppSettingsRolesIndexRoute
  '/_portal/portal/$pipelineId/': typeof PortalPortalPipelineIdIndexRoute
  '/_app/settings/forms/$formId/preview': typeof AppSettingsFormsFormIdPreviewRoute
  '/_app/settings/forms/$formId/submissions': typeof AppSettingsFormsFormIdSubmissionsRoute
  '/_app/settings/roles/$roleId/edit': typeof AppSettingsRolesRoleIdEditRoute
  '/_app/settings/forms/$formId/': typeof AppSettingsFormsFormIdIndexRoute
  '/_app/settings/roles/$roleId/': typeof AppSettingsRolesRoleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/announcements'
    | '/dashboard'
    | '/employees'
    | '/me'
    | '/notifications'
    | '/org-chart'
    | '/settings'
    | '/login'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tenants'
    | '/attendance/records'
    | '/attendance/regularization'
    | '/attendance/team'
    | '/candidates/$candidateId'
    | '/candidates/invite'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/expenses/new'
    | '/helpdesk/new'
    | '/leave/apply'
    | '/leave/approvals'
    | '/leave/balances'
    | '/leave/calendar'
    | '/leave/requests'
    | '/payroll/declarations'
    | '/payroll/payslips'
    | '/performance/admin'
    | '/performance/calibration'
    | '/performance/goals'
    | '/performance/reviews'
    | '/performance/team'
    | '/reports/$reportSlug'
    | '/settings/attendance'
    | '/settings/company'
    | '/settings/roles'
    | '/onboarding/admin'
    | '/onboarding/brand'
    | '/onboarding/review'
    | '/attendance/'
    | '/candidates/'
    | '/employees/'
    | '/expenses/'
    | '/helpdesk/'
    | '/leave/'
    | '/payroll/'
    | '/performance/'
    | '/reports/'
    | '/portal/'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/new'
    | '/attendance/regularization/approvals'
    | '/employees/$employeeId/edit'
    | '/payroll/runs/$runId'
    | '/performance/reviews/$reviewId'
    | '/performance/team/$employeeId'
    | '/reports/builder/$reportId'
    | '/settings/company/departments'
    | '/settings/company/designations'
    | '/settings/company/holidays'
    | '/settings/company/work-calendar'
    | '/settings/forms/new'
    | '/settings/hiring/rejection-reasons'
    | '/settings/leave/policies'
    | '/settings/payroll/structures'
    | '/settings/roles/assignments'
    | '/settings/roles/audit'
    | '/settings/roles/delegation'
    | '/settings/roles/new'
    | '/portal/$pipelineId/form'
    | '/portal/$pipelineId/offer'
    | '/attendance/regularization/'
    | '/payroll/runs/'
    | '/reports/builder/'
    | '/settings/forms/'
    | '/settings/leave/'
    | '/settings/payroll/'
    | '/settings/roles/'
    | '/portal/$pipelineId/'
    | '/settings/forms/$formId/preview'
    | '/settings/forms/$formId/submissions'
    | '/settings/roles/$roleId/edit'
    | '/settings/forms/$formId/'
    | '/settings/roles/$roleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/announcements'
    | '/dashboard'
    | '/me'
    | '/notifications'
    | '/org-chart'
    | '/settings'
    | '/login'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tenants'
    | '/attendance/records'
    | '/attendance/team'
    | '/candidates/$candidateId'
    | '/candidates/invite'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/expenses/new'
    | '/helpdesk/new'
    | '/leave/apply'
    | '/leave/approvals'
    | '/leave/balances'
    | '/leave/calendar'
    | '/leave/requests'
    | '/payroll/declarations'
    | '/payroll/payslips'
    | '/performance/admin'
    | '/performance/calibration'
    | '/performance/goals'
    | '/performance/reviews'
    | '/performance/team'
    | '/reports/$reportSlug'
    | '/settings/attendance'
    | '/settings/company'
    | '/onboarding/admin'
    | '/onboarding/brand'
    | '/onboarding/review'
    | '/attendance'
    | '/candidates'
    | '/employees'
    | '/expenses'
    | '/helpdesk'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/portal'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/new'
    | '/attendance/regularization/approvals'
    | '/employees/$employeeId/edit'
    | '/payroll/runs/$runId'
    | '/performance/reviews/$reviewId'
    | '/performance/team/$employeeId'
    | '/reports/builder/$reportId'
    | '/settings/company/departments'
    | '/settings/company/designations'
    | '/settings/company/holidays'
    | '/settings/company/work-calendar'
    | '/settings/forms/new'
    | '/settings/hiring/rejection-reasons'
    | '/settings/leave/policies'
    | '/settings/payroll/structures'
    | '/settings/roles/assignments'
    | '/settings/roles/audit'
    | '/settings/roles/delegation'
    | '/settings/roles/new'
    | '/portal/$pipelineId/form'
    | '/portal/$pipelineId/offer'
    | '/attendance/regularization'
    | '/payroll/runs'
    | '/reports/builder'
    | '/settings/forms'
    | '/settings/leave'
    | '/settings/payroll'
    | '/settings/roles'
    | '/portal/$pipelineId'
    | '/settings/forms/$formId/preview'
    | '/settings/forms/$formId/submissions'
    | '/settings/roles/$roleId/edit'
    | '/settings/forms/$formId'
    | '/settings/roles/$roleId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/_platform'
    | '/_portal'
    | '/_app/ai-assistant'
    | '/_app/announcements'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/me'
    | '/_app/notifications'
    | '/_app/org-chart'
    | '/_app/settings'
    | '/_platform/login'
    | '/_platform/onboarding'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/login'
    | '/_admin/admin/settings'
    | '/_admin/admin/tenants'
    | '/_app/attendance/records'
    | '/_app/attendance/regularization'
    | '/_app/attendance/team'
    | '/_app/candidates/$candidateId'
    | '/_app/candidates/invite'
    | '/_app/employees/$employeeId'
    | '/_app/employees/new'
    | '/_app/expenses/new'
    | '/_app/helpdesk/new'
    | '/_app/leave/apply'
    | '/_app/leave/approvals'
    | '/_app/leave/balances'
    | '/_app/leave/calendar'
    | '/_app/leave/requests'
    | '/_app/payroll/declarations'
    | '/_app/payroll/payslips'
    | '/_app/performance/admin'
    | '/_app/performance/calibration'
    | '/_app/performance/goals'
    | '/_app/performance/reviews'
    | '/_app/performance/team'
    | '/_app/reports/$reportSlug'
    | '/_app/settings/attendance'
    | '/_app/settings/company'
    | '/_app/settings/roles'
    | '/_platform/onboarding/admin'
    | '/_platform/onboarding/brand'
    | '/_platform/onboarding/review'
    | '/_app/attendance/'
    | '/_app/candidates/'
    | '/_app/employees/'
    | '/_app/expenses/'
    | '/_app/helpdesk/'
    | '/_app/leave/'
    | '/_app/payroll/'
    | '/_app/performance/'
    | '/_app/reports/'
    | '/_portal/portal/'
    | '/_admin/admin/tenants/$tenantId'
    | '/_admin/admin/tenants/new'
    | '/_app/attendance/regularization/approvals'
    | '/_app/employees/$employeeId/edit'
    | '/_app/payroll/runs/$runId'
    | '/_app/performance/reviews/$reviewId'
    | '/_app/performance/team/$employeeId'
    | '/_app/reports/builder/$reportId'
    | '/_app/settings/company/departments'
    | '/_app/settings/company/designations'
    | '/_app/settings/company/holidays'
    | '/_app/settings/company/work-calendar'
    | '/_app/settings/forms/new'
    | '/_app/settings/hiring/rejection-reasons'
    | '/_app/settings/leave/policies'
    | '/_app/settings/payroll/structures'
    | '/_app/settings/roles/assignments'
    | '/_app/settings/roles/audit'
    | '/_app/settings/roles/delegation'
    | '/_app/settings/roles/new'
    | '/_portal/portal/$pipelineId/form'
    | '/_portal/portal/$pipelineId/offer'
    | '/_app/attendance/regularization/'
    | '/_app/payroll/runs/'
    | '/_app/reports/builder/'
    | '/_app/settings/forms/'
    | '/_app/settings/leave/'
    | '/_app/settings/payroll/'
    | '/_app/settings/roles/'
    | '/_portal/portal/$pipelineId/'
    | '/_app/settings/forms/$formId/preview'
    | '/_app/settings/forms/$formId/submissions'
    | '/_app/settings/roles/$roleId/edit'
    | '/_app/settings/forms/$formId/'
    | '/_app/settings/roles/$roleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/onboarding': {
      id: '/_platform/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PlatformOnboardingRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/login': {
      id: '/_platform/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org-chart': {
      id: '/_app/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof AppOrgChartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/': {
      id: '/_app/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof AppPerformanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/': {
      id: '/_app/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof AppLeaveIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/helpdesk/': {
      id: '/_app/helpdesk/'
      path: '/helpdesk'
      fullPath: '/helpdesk/'
      preLoaderRoute: typeof AppHelpdeskIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/candidates/': {
      id: '/_app/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_platform/onboarding/review': {
      id: '/_platform/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof PlatformOnboardingReviewRouteImport
      parentRoute: typeof PlatformOnboardingRoute
    }
    '/_platform/onboarding/brand': {
      id: '/_platform/onboarding/brand'
      path: '/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof PlatformOnboardingBrandRouteImport
      parentRoute: typeof PlatformOnboardingRoute
    }
    '/_platform/onboarding/admin': {
      id: '/_platform/onboarding/admin'
      path: '/admin'
      fullPath: '/onboarding/admin'
      preLoaderRoute: typeof PlatformOnboardingAdminRouteImport
      parentRoute: typeof PlatformOnboardingRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/attendance': {
      id: '/_app/settings/attendance'
      path: '/attendance'
      fullPath: '/settings/attendance'
      preLoaderRoute: typeof AppSettingsAttendanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reports/$reportSlug': {
      id: '/_app/reports/$reportSlug'
      path: '/reports/$reportSlug'
      fullPath: '/reports/$reportSlug'
      preLoaderRoute: typeof AppReportsReportSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/team': {
      id: '/_app/performance/team'
      path: '/performance/team'
      fullPath: '/performance/team'
      preLoaderRoute: typeof AppPerformanceTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/reviews': {
      id: '/_app/performance/reviews'
      path: '/performance/reviews'
      fullPath: '/performance/reviews'
      preLoaderRoute: typeof AppPerformanceReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/goals': {
      id: '/_app/performance/goals'
      path: '/performance/goals'
      fullPath: '/performance/goals'
      preLoaderRoute: typeof AppPerformanceGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/calibration': {
      id: '/_app/performance/calibration'
      path: '/performance/calibration'
      fullPath: '/performance/calibration'
      preLoaderRoute: typeof AppPerformanceCalibrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/admin': {
      id: '/_app/performance/admin'
      path: '/performance/admin'
      fullPath: '/performance/admin'
      preLoaderRoute: typeof AppPerformanceAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/payslips': {
      id: '/_app/payroll/payslips'
      path: '/payroll/payslips'
      fullPath: '/payroll/payslips'
      preLoaderRoute: typeof AppPayrollPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/declarations': {
      id: '/_app/payroll/declarations'
      path: '/payroll/declarations'
      fullPath: '/payroll/declarations'
      preLoaderRoute: typeof AppPayrollDeclarationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/requests': {
      id: '/_app/leave/requests'
      path: '/leave/requests'
      fullPath: '/leave/requests'
      preLoaderRoute: typeof AppLeaveRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/calendar': {
      id: '/_app/leave/calendar'
      path: '/leave/calendar'
      fullPath: '/leave/calendar'
      preLoaderRoute: typeof AppLeaveCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/balances': {
      id: '/_app/leave/balances'
      path: '/leave/balances'
      fullPath: '/leave/balances'
      preLoaderRoute: typeof AppLeaveBalancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/approvals': {
      id: '/_app/leave/approvals'
      path: '/leave/approvals'
      fullPath: '/leave/approvals'
      preLoaderRoute: typeof AppLeaveApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/apply': {
      id: '/_app/leave/apply'
      path: '/leave/apply'
      fullPath: '/leave/apply'
      preLoaderRoute: typeof AppLeaveApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/helpdesk/new': {
      id: '/_app/helpdesk/new'
      path: '/helpdesk/new'
      fullPath: '/helpdesk/new'
      preLoaderRoute: typeof AppHelpdeskNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/new': {
      id: '/_app/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/new': {
      id: '/_app/employees/new'
      path: '/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AppEmployeesNewRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/candidates/invite': {
      id: '/_app/candidates/invite'
      path: '/candidates/invite'
      fullPath: '/candidates/invite'
      preLoaderRoute: typeof AppCandidatesInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates/$candidateId': {
      id: '/_app/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AppCandidatesCandidateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/team': {
      id: '/_app/attendance/team'
      path: '/attendance/team'
      fullPath: '/attendance/team'
      preLoaderRoute: typeof AppAttendanceTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/regularization': {
      id: '/_app/attendance/regularization'
      path: '/attendance/regularization'
      fullPath: '/attendance/regularization'
      preLoaderRoute: typeof AppAttendanceRegularizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/records': {
      id: '/_app/attendance/records'
      path: '/attendance/records'
      fullPath: '/attendance/records'
      preLoaderRoute: typeof AppAttendanceRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/tenants': {
      id: '/_admin/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminAdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/portal/$pipelineId/': {
      id: '/_portal/portal/$pipelineId/'
      path: '/portal/$pipelineId'
      fullPath: '/portal/$pipelineId/'
      preLoaderRoute: typeof PortalPortalPipelineIdIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/settings/roles/': {
      id: '/_app/settings/roles/'
      path: '/'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof AppSettingsRolesIndexRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/payroll/': {
      id: '/_app/settings/payroll/'
      path: '/payroll'
      fullPath: '/settings/payroll/'
      preLoaderRoute: typeof AppSettingsPayrollIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/leave/': {
      id: '/_app/settings/leave/'
      path: '/leave'
      fullPath: '/settings/leave/'
      preLoaderRoute: typeof AppSettingsLeaveIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/forms/': {
      id: '/_app/settings/forms/'
      path: '/forms'
      fullPath: '/settings/forms/'
      preLoaderRoute: typeof AppSettingsFormsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reports/builder/': {
      id: '/_app/reports/builder/'
      path: '/reports/builder'
      fullPath: '/reports/builder/'
      preLoaderRoute: typeof AppReportsBuilderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/runs/': {
      id: '/_app/payroll/runs/'
      path: '/payroll/runs'
      fullPath: '/payroll/runs/'
      preLoaderRoute: typeof AppPayrollRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/regularization/': {
      id: '/_app/attendance/regularization/'
      path: '/'
      fullPath: '/attendance/regularization/'
      preLoaderRoute: typeof AppAttendanceRegularizationIndexRouteImport
      parentRoute: typeof AppAttendanceRegularizationRoute
    }
    '/_portal/portal/$pipelineId/offer': {
      id: '/_portal/portal/$pipelineId/offer'
      path: '/portal/$pipelineId/offer'
      fullPath: '/portal/$pipelineId/offer'
      preLoaderRoute: typeof PortalPortalPipelineIdOfferRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/$pipelineId/form': {
      id: '/_portal/portal/$pipelineId/form'
      path: '/portal/$pipelineId/form'
      fullPath: '/portal/$pipelineId/form'
      preLoaderRoute: typeof PortalPortalPipelineIdFormRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/settings/roles/new': {
      id: '/_app/settings/roles/new'
      path: '/new'
      fullPath: '/settings/roles/new'
      preLoaderRoute: typeof AppSettingsRolesNewRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/roles/delegation': {
      id: '/_app/settings/roles/delegation'
      path: '/delegation'
      fullPath: '/settings/roles/delegation'
      preLoaderRoute: typeof AppSettingsRolesDelegationRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/roles/audit': {
      id: '/_app/settings/roles/audit'
      path: '/audit'
      fullPath: '/settings/roles/audit'
      preLoaderRoute: typeof AppSettingsRolesAuditRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/roles/assignments': {
      id: '/_app/settings/roles/assignments'
      path: '/assignments'
      fullPath: '/settings/roles/assignments'
      preLoaderRoute: typeof AppSettingsRolesAssignmentsRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/payroll/structures': {
      id: '/_app/settings/payroll/structures'
      path: '/payroll/structures'
      fullPath: '/settings/payroll/structures'
      preLoaderRoute: typeof AppSettingsPayrollStructuresRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/leave/policies': {
      id: '/_app/settings/leave/policies'
      path: '/leave/policies'
      fullPath: '/settings/leave/policies'
      preLoaderRoute: typeof AppSettingsLeavePoliciesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/hiring/rejection-reasons': {
      id: '/_app/settings/hiring/rejection-reasons'
      path: '/hiring/rejection-reasons'
      fullPath: '/settings/hiring/rejection-reasons'
      preLoaderRoute: typeof AppSettingsHiringRejectionReasonsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/forms/new': {
      id: '/_app/settings/forms/new'
      path: '/forms/new'
      fullPath: '/settings/forms/new'
      preLoaderRoute: typeof AppSettingsFormsNewRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/company/work-calendar': {
      id: '/_app/settings/company/work-calendar'
      path: '/work-calendar'
      fullPath: '/settings/company/work-calendar'
      preLoaderRoute: typeof AppSettingsCompanyWorkCalendarRouteImport
      parentRoute: typeof AppSettingsCompanyRoute
    }
    '/_app/settings/company/holidays': {
      id: '/_app/settings/company/holidays'
      path: '/holidays'
      fullPath: '/settings/company/holidays'
      preLoaderRoute: typeof AppSettingsCompanyHolidaysRouteImport
      parentRoute: typeof AppSettingsCompanyRoute
    }
    '/_app/settings/company/designations': {
      id: '/_app/settings/company/designations'
      path: '/designations'
      fullPath: '/settings/company/designations'
      preLoaderRoute: typeof AppSettingsCompanyDesignationsRouteImport
      parentRoute: typeof AppSettingsCompanyRoute
    }
    '/_app/settings/company/departments': {
      id: '/_app/settings/company/departments'
      path: '/departments'
      fullPath: '/settings/company/departments'
      preLoaderRoute: typeof AppSettingsCompanyDepartmentsRouteImport
      parentRoute: typeof AppSettingsCompanyRoute
    }
    '/_app/reports/builder/$reportId': {
      id: '/_app/reports/builder/$reportId'
      path: '/reports/builder/$reportId'
      fullPath: '/reports/builder/$reportId'
      preLoaderRoute: typeof AppReportsBuilderReportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/team/$employeeId': {
      id: '/_app/performance/team/$employeeId'
      path: '/$employeeId'
      fullPath: '/performance/team/$employeeId'
      preLoaderRoute: typeof AppPerformanceTeamEmployeeIdRouteImport
      parentRoute: typeof AppPerformanceTeamRoute
    }
    '/_app/performance/reviews/$reviewId': {
      id: '/_app/performance/reviews/$reviewId'
      path: '/$reviewId'
      fullPath: '/performance/reviews/$reviewId'
      preLoaderRoute: typeof AppPerformanceReviewsReviewIdRouteImport
      parentRoute: typeof AppPerformanceReviewsRoute
    }
    '/_app/payroll/runs/$runId': {
      id: '/_app/payroll/runs/$runId'
      path: '/payroll/runs/$runId'
      fullPath: '/payroll/runs/$runId'
      preLoaderRoute: typeof AppPayrollRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$employeeId/edit': {
      id: '/_app/employees/$employeeId/edit'
      path: '/edit'
      fullPath: '/employees/$employeeId/edit'
      preLoaderRoute: typeof AppEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof AppEmployeesEmployeeIdRoute
    }
    '/_app/attendance/regularization/approvals': {
      id: '/_app/attendance/regularization/approvals'
      path: '/approvals'
      fullPath: '/attendance/regularization/approvals'
      preLoaderRoute: typeof AppAttendanceRegularizationApprovalsRouteImport
      parentRoute: typeof AppAttendanceRegularizationRoute
    }
    '/_admin/admin/tenants/new': {
      id: '/_admin/admin/tenants/new'
      path: '/new'
      fullPath: '/admin/tenants/new'
      preLoaderRoute: typeof AdminAdminTenantsNewRouteImport
      parentRoute: typeof AdminAdminTenantsRoute
    }
    '/_admin/admin/tenants/$tenantId': {
      id: '/_admin/admin/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminAdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminAdminTenantsRoute
    }
    '/_app/settings/roles/$roleId/': {
      id: '/_app/settings/roles/$roleId/'
      path: '/$roleId'
      fullPath: '/settings/roles/$roleId/'
      preLoaderRoute: typeof AppSettingsRolesRoleIdIndexRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/forms/$formId/': {
      id: '/_app/settings/forms/$formId/'
      path: '/forms/$formId'
      fullPath: '/settings/forms/$formId/'
      preLoaderRoute: typeof AppSettingsFormsFormIdIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/roles/$roleId/edit': {
      id: '/_app/settings/roles/$roleId/edit'
      path: '/$roleId/edit'
      fullPath: '/settings/roles/$roleId/edit'
      preLoaderRoute: typeof AppSettingsRolesRoleIdEditRouteImport
      parentRoute: typeof AppSettingsRolesRoute
    }
    '/_app/settings/forms/$formId/submissions': {
      id: '/_app/settings/forms/$formId/submissions'
      path: '/forms/$formId/submissions'
      fullPath: '/settings/forms/$formId/submissions'
      preLoaderRoute: typeof AppSettingsFormsFormIdSubmissionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/forms/$formId/preview': {
      id: '/_app/settings/forms/$formId/preview'
      path: '/forms/$formId/preview'
      fullPath: '/settings/forms/$formId/preview'
      preLoaderRoute: typeof AppSettingsFormsFormIdPreviewRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AdminAdminTenantsRouteChildren {
  AdminAdminTenantsTenantIdRoute: typeof AdminAdminTenantsTenantIdRoute
  AdminAdminTenantsNewRoute: typeof AdminAdminTenantsNewRoute
}

const AdminAdminTenantsRouteChildren: AdminAdminTenantsRouteChildren = {
  AdminAdminTenantsTenantIdRoute: AdminAdminTenantsTenantIdRoute,
  AdminAdminTenantsNewRoute: AdminAdminTenantsNewRoute,
}

const AdminAdminTenantsRouteWithChildren =
  AdminAdminTenantsRoute._addFileChildren(AdminAdminTenantsRouteChildren)

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminTenantsRoute: typeof AdminAdminTenantsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminTenantsRoute: AdminAdminTenantsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEmployeesEmployeeIdRouteChildren {
  AppEmployeesEmployeeIdEditRoute: typeof AppEmployeesEmployeeIdEditRoute
}

const AppEmployeesEmployeeIdRouteChildren: AppEmployeesEmployeeIdRouteChildren =
  {
    AppEmployeesEmployeeIdEditRoute: AppEmployeesEmployeeIdEditRoute,
  }

const AppEmployeesEmployeeIdRouteWithChildren =
  AppEmployeesEmployeeIdRoute._addFileChildren(
    AppEmployeesEmployeeIdRouteChildren,
  )

interface AppEmployeesRouteChildren {
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRouteWithChildren
  AppEmployeesNewRoute: typeof AppEmployeesNewRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRouteWithChildren,
  AppEmployeesNewRoute: AppEmployeesNewRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppSettingsCompanyRouteChildren {
  AppSettingsCompanyDepartmentsRoute: typeof AppSettingsCompanyDepartmentsRoute
  AppSettingsCompanyDesignationsRoute: typeof AppSettingsCompanyDesignationsRoute
  AppSettingsCompanyHolidaysRoute: typeof AppSettingsCompanyHolidaysRoute
  AppSettingsCompanyWorkCalendarRoute: typeof AppSettingsCompanyWorkCalendarRoute
}

const AppSettingsCompanyRouteChildren: AppSettingsCompanyRouteChildren = {
  AppSettingsCompanyDepartmentsRoute: AppSettingsCompanyDepartmentsRoute,
  AppSettingsCompanyDesignationsRoute: AppSettingsCompanyDesignationsRoute,
  AppSettingsCompanyHolidaysRoute: AppSettingsCompanyHolidaysRoute,
  AppSettingsCompanyWorkCalendarRoute: AppSettingsCompanyWorkCalendarRoute,
}

const AppSettingsCompanyRouteWithChildren =
  AppSettingsCompanyRoute._addFileChildren(AppSettingsCompanyRouteChildren)

interface AppSettingsRolesRouteChildren {
  AppSettingsRolesAssignmentsRoute: typeof AppSettingsRolesAssignmentsRoute
  AppSettingsRolesAuditRoute: typeof AppSettingsRolesAuditRoute
  AppSettingsRolesDelegationRoute: typeof AppSettingsRolesDelegationRoute
  AppSettingsRolesNewRoute: typeof AppSettingsRolesNewRoute
  AppSettingsRolesIndexRoute: typeof AppSettingsRolesIndexRoute
  AppSettingsRolesRoleIdEditRoute: typeof AppSettingsRolesRoleIdEditRoute
  AppSettingsRolesRoleIdIndexRoute: typeof AppSettingsRolesRoleIdIndexRoute
}

const AppSettingsRolesRouteChildren: AppSettingsRolesRouteChildren = {
  AppSettingsRolesAssignmentsRoute: AppSettingsRolesAssignmentsRoute,
  AppSettingsRolesAuditRoute: AppSettingsRolesAuditRoute,
  AppSettingsRolesDelegationRoute: AppSettingsRolesDelegationRoute,
  AppSettingsRolesNewRoute: AppSettingsRolesNewRoute,
  AppSettingsRolesIndexRoute: AppSettingsRolesIndexRoute,
  AppSettingsRolesRoleIdEditRoute: AppSettingsRolesRoleIdEditRoute,
  AppSettingsRolesRoleIdIndexRoute: AppSettingsRolesRoleIdIndexRoute,
}

const AppSettingsRolesRouteWithChildren =
  AppSettingsRolesRoute._addFileChildren(AppSettingsRolesRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAttendanceRoute: typeof AppSettingsAttendanceRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRouteWithChildren
  AppSettingsRolesRoute: typeof AppSettingsRolesRouteWithChildren
  AppSettingsFormsNewRoute: typeof AppSettingsFormsNewRoute
  AppSettingsHiringRejectionReasonsRoute: typeof AppSettingsHiringRejectionReasonsRoute
  AppSettingsLeavePoliciesRoute: typeof AppSettingsLeavePoliciesRoute
  AppSettingsPayrollStructuresRoute: typeof AppSettingsPayrollStructuresRoute
  AppSettingsFormsIndexRoute: typeof AppSettingsFormsIndexRoute
  AppSettingsLeaveIndexRoute: typeof AppSettingsLeaveIndexRoute
  AppSettingsPayrollIndexRoute: typeof AppSettingsPayrollIndexRoute
  AppSettingsFormsFormIdPreviewRoute: typeof AppSettingsFormsFormIdPreviewRoute
  AppSettingsFormsFormIdSubmissionsRoute: typeof AppSettingsFormsFormIdSubmissionsRoute
  AppSettingsFormsFormIdIndexRoute: typeof AppSettingsFormsFormIdIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAttendanceRoute: AppSettingsAttendanceRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRouteWithChildren,
  AppSettingsRolesRoute: AppSettingsRolesRouteWithChildren,
  AppSettingsFormsNewRoute: AppSettingsFormsNewRoute,
  AppSettingsHiringRejectionReasonsRoute:
    AppSettingsHiringRejectionReasonsRoute,
  AppSettingsLeavePoliciesRoute: AppSettingsLeavePoliciesRoute,
  AppSettingsPayrollStructuresRoute: AppSettingsPayrollStructuresRoute,
  AppSettingsFormsIndexRoute: AppSettingsFormsIndexRoute,
  AppSettingsLeaveIndexRoute: AppSettingsLeaveIndexRoute,
  AppSettingsPayrollIndexRoute: AppSettingsPayrollIndexRoute,
  AppSettingsFormsFormIdPreviewRoute: AppSettingsFormsFormIdPreviewRoute,
  AppSettingsFormsFormIdSubmissionsRoute:
    AppSettingsFormsFormIdSubmissionsRoute,
  AppSettingsFormsFormIdIndexRoute: AppSettingsFormsFormIdIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppAttendanceRegularizationRouteChildren {
  AppAttendanceRegularizationApprovalsRoute: typeof AppAttendanceRegularizationApprovalsRoute
  AppAttendanceRegularizationIndexRoute: typeof AppAttendanceRegularizationIndexRoute
}

const AppAttendanceRegularizationRouteChildren: AppAttendanceRegularizationRouteChildren =
  {
    AppAttendanceRegularizationApprovalsRoute:
      AppAttendanceRegularizationApprovalsRoute,
    AppAttendanceRegularizationIndexRoute:
      AppAttendanceRegularizationIndexRoute,
  }

const AppAttendanceRegularizationRouteWithChildren =
  AppAttendanceRegularizationRoute._addFileChildren(
    AppAttendanceRegularizationRouteChildren,
  )

interface AppPerformanceReviewsRouteChildren {
  AppPerformanceReviewsReviewIdRoute: typeof AppPerformanceReviewsReviewIdRoute
}

const AppPerformanceReviewsRouteChildren: AppPerformanceReviewsRouteChildren = {
  AppPerformanceReviewsReviewIdRoute: AppPerformanceReviewsReviewIdRoute,
}

const AppPerformanceReviewsRouteWithChildren =
  AppPerformanceReviewsRoute._addFileChildren(
    AppPerformanceReviewsRouteChildren,
  )

interface AppPerformanceTeamRouteChildren {
  AppPerformanceTeamEmployeeIdRoute: typeof AppPerformanceTeamEmployeeIdRoute
}

const AppPerformanceTeamRouteChildren: AppPerformanceTeamRouteChildren = {
  AppPerformanceTeamEmployeeIdRoute: AppPerformanceTeamEmployeeIdRoute,
}

const AppPerformanceTeamRouteWithChildren =
  AppPerformanceTeamRoute._addFileChildren(AppPerformanceTeamRouteChildren)

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppMeRoute: typeof AppMeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrgChartRoute: typeof AppOrgChartRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppAttendanceRecordsRoute: typeof AppAttendanceRecordsRoute
  AppAttendanceRegularizationRoute: typeof AppAttendanceRegularizationRouteWithChildren
  AppAttendanceTeamRoute: typeof AppAttendanceTeamRoute
  AppCandidatesCandidateIdRoute: typeof AppCandidatesCandidateIdRoute
  AppCandidatesInviteRoute: typeof AppCandidatesInviteRoute
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppHelpdeskNewRoute: typeof AppHelpdeskNewRoute
  AppLeaveApplyRoute: typeof AppLeaveApplyRoute
  AppLeaveApprovalsRoute: typeof AppLeaveApprovalsRoute
  AppLeaveBalancesRoute: typeof AppLeaveBalancesRoute
  AppLeaveCalendarRoute: typeof AppLeaveCalendarRoute
  AppLeaveRequestsRoute: typeof AppLeaveRequestsRoute
  AppPayrollDeclarationsRoute: typeof AppPayrollDeclarationsRoute
  AppPayrollPayslipsRoute: typeof AppPayrollPayslipsRoute
  AppPerformanceAdminRoute: typeof AppPerformanceAdminRoute
  AppPerformanceCalibrationRoute: typeof AppPerformanceCalibrationRoute
  AppPerformanceGoalsRoute: typeof AppPerformanceGoalsRoute
  AppPerformanceReviewsRoute: typeof AppPerformanceReviewsRouteWithChildren
  AppPerformanceTeamRoute: typeof AppPerformanceTeamRouteWithChildren
  AppReportsReportSlugRoute: typeof AppReportsReportSlugRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppHelpdeskIndexRoute: typeof AppHelpdeskIndexRoute
  AppLeaveIndexRoute: typeof AppLeaveIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppPerformanceIndexRoute: typeof AppPerformanceIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppPayrollRunsRunIdRoute: typeof AppPayrollRunsRunIdRoute
  AppReportsBuilderReportIdRoute: typeof AppReportsBuilderReportIdRoute
  AppPayrollRunsIndexRoute: typeof AppPayrollRunsIndexRoute
  AppReportsBuilderIndexRoute: typeof AppReportsBuilderIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppMeRoute: AppMeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrgChartRoute: AppOrgChartRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppAttendanceRecordsRoute: AppAttendanceRecordsRoute,
  AppAttendanceRegularizationRoute:
    AppAttendanceRegularizationRouteWithChildren,
  AppAttendanceTeamRoute: AppAttendanceTeamRoute,
  AppCandidatesCandidateIdRoute: AppCandidatesCandidateIdRoute,
  AppCandidatesInviteRoute: AppCandidatesInviteRoute,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppHelpdeskNewRoute: AppHelpdeskNewRoute,
  AppLeaveApplyRoute: AppLeaveApplyRoute,
  AppLeaveApprovalsRoute: AppLeaveApprovalsRoute,
  AppLeaveBalancesRoute: AppLeaveBalancesRoute,
  AppLeaveCalendarRoute: AppLeaveCalendarRoute,
  AppLeaveRequestsRoute: AppLeaveRequestsRoute,
  AppPayrollDeclarationsRoute: AppPayrollDeclarationsRoute,
  AppPayrollPayslipsRoute: AppPayrollPayslipsRoute,
  AppPerformanceAdminRoute: AppPerformanceAdminRoute,
  AppPerformanceCalibrationRoute: AppPerformanceCalibrationRoute,
  AppPerformanceGoalsRoute: AppPerformanceGoalsRoute,
  AppPerformanceReviewsRoute: AppPerformanceReviewsRouteWithChildren,
  AppPerformanceTeamRoute: AppPerformanceTeamRouteWithChildren,
  AppReportsReportSlugRoute: AppReportsReportSlugRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppHelpdeskIndexRoute: AppHelpdeskIndexRoute,
  AppLeaveIndexRoute: AppLeaveIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppPerformanceIndexRoute: AppPerformanceIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppPayrollRunsRunIdRoute: AppPayrollRunsRunIdRoute,
  AppReportsBuilderReportIdRoute: AppReportsBuilderReportIdRoute,
  AppPayrollRunsIndexRoute: AppPayrollRunsIndexRoute,
  AppReportsBuilderIndexRoute: AppReportsBuilderIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformOnboardingRouteChildren {
  PlatformOnboardingAdminRoute: typeof PlatformOnboardingAdminRoute
  PlatformOnboardingBrandRoute: typeof PlatformOnboardingBrandRoute
  PlatformOnboardingReviewRoute: typeof PlatformOnboardingReviewRoute
}

const PlatformOnboardingRouteChildren: PlatformOnboardingRouteChildren = {
  PlatformOnboardingAdminRoute: PlatformOnboardingAdminRoute,
  PlatformOnboardingBrandRoute: PlatformOnboardingBrandRoute,
  PlatformOnboardingReviewRoute: PlatformOnboardingReviewRoute,
}

const PlatformOnboardingRouteWithChildren =
  PlatformOnboardingRoute._addFileChildren(PlatformOnboardingRouteChildren)

interface PlatformRouteChildren {
  PlatformLoginRoute: typeof PlatformLoginRoute
  PlatformOnboardingRoute: typeof PlatformOnboardingRouteWithChildren
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformLoginRoute: PlatformLoginRoute,
  PlatformOnboardingRoute: PlatformOnboardingRouteWithChildren,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface PortalRouteChildren {
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
  PortalPortalPipelineIdFormRoute: typeof PortalPortalPipelineIdFormRoute
  PortalPortalPipelineIdOfferRoute: typeof PortalPortalPipelineIdOfferRoute
  PortalPortalPipelineIdIndexRoute: typeof PortalPortalPipelineIdIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPortalIndexRoute: PortalPortalIndexRoute,
  PortalPortalPipelineIdFormRoute: PortalPortalPipelineIdFormRoute,
  PortalPortalPipelineIdOfferRoute: PortalPortalPipelineIdOfferRoute,
  PortalPortalPipelineIdIndexRoute: PortalPortalPipelineIdIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
